version: 2
jobs:
  build-test:
    working_directory: '~/sam-modal'
    docker:
      - image: eu.gcr.io/sam-non-production/circle-gsdk-firebase-node-v2
        auth:
          username: _json_key
          password: $GCLOUD_CONTAINER_REGISTRY_SERVICE_KEY 
    steps:
      - checkout
      - run:
          name: build
          command: |
            yarn
            yarn build
      - store_artifacts:
          path: package-lock.json
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: '~/sam-modal'
    docker:
      - image: eu.gcr.io/sam-non-production/circle-gsdk-firebase-node-v2
        auth:
          username: _json_key
          password: $GCLOUD_CONTAINER_REGISTRY_SERVICE_KEY 
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/sam-modal/.npmrc
      - run:
          name: NPM-Deploy
          command: |
            cd ~/sam-modal
            echo "Add Version Number"
            npm version ${CIRCLE_TAG} -f -no-git --no-git-tag-version

            echo "Update NPM"
            npm publish --access public .
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            tags:
              only:
                - /^[0-9]+(\.[0-9]+)*$/
      - deploy:
          requires:
            - build-test
          filters:
            tags:
              only:
                - /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore:
                - /.*/